// ============================================================
// script.js — Dune & Bean
//   1. Lenis smooth scroll (desktop/pointer only, respects
//      prefers-reduced-motion, no-op on touch devices)
//   2. Page transitions (deterministic JS/CSS, cross-document)
//   3. Header chrome (mobile nav, active link)
//   4. Scroll-triggered reveals
//   5. Smooth anchor navigation (Lenis-aware, with fallback)
// ============================================================

/* ── Current year in footer ── */
document.getElementById('year').textContent = new Date().getFullYear();

/* ── Lenis smooth scroll ──────────────────────────────────── */
const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const isCoarsePointer = window.matchMedia('(pointer: coarse)').matches;

let lenis = null;

if (!prefersReducedMotion && !isCoarsePointer && window.Lenis) {
  lenis = new Lenis({
      duration: 1.15,
          easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
              smoothWheel: true,
                  touchMultiplier: 0, // native scroll on any touch input that slips through
                    });

                      const raf = (time) => {
                          lenis.raf(time);
                              requestAnimationFrame(raf);
                                };
                                  requestAnimationFrame(raf);
                                  }

                                  /* ── Page transitions — deterministic JS/CSS ──────────────────
                                     Replaces the View Transitions API (unreliable across repeat
                                        navigations in real sessions). This is plain JS + a CSS
                                           transition on <body>: no experimental feature, no feature
                                              detection, no fallback path needed — it behaves identically
                                                 in every browser.

                                                    Every page's <body> already carries class="page-enter" in its
                                                       HTML (not added here), so it starts hidden/offset at first
                                                          paint with zero flash. On load we clear that class one frame
                                                             later so the browser actually animates the change instead of
                                                                skipping it. On click, we intercept internal .html links, play
                                                                   the exit state, and navigate on a plain timer — the timer, not
                                                                      an event, is what guarantees the next page always loads. ── */
                                                                      const PAGE_TRANSITION_MS = 400;

                                                                      if (!prefersReducedMotion) {
                                                                        requestAnimationFrame(() => {
                                                                            requestAnimationFrame(() => {
                                                                                  document.body.classList.remove('page-enter');
                                                                                      });
                                                                                        });

                                                                                          let transitioning = false;

                                                                                            document.querySelectorAll('a[href$=".html"]').forEach((link) => {
                                                                                                link.addEventListener('click', (e) => {
                                                                                                      if (transitioning) {
                                                                                                              e.preventDefault();
                                                                                                                      return;
                                                                                                                            }
                                                                                                                                  // Let modified/new-tab clicks behave normally — only a plain
                                                                                                                                        // left click gets the animated hand-off.
                                                                                                                                              if (link.target === '_blank' || e.button !== 0 ||
                                                                                                                                                        e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) {
                                                                                                                                                                return;
                                                                                                                                                                      }
                                                                                                                                                                      
                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                  transitioning = true;
                                                                                                                                                                                        document.body.classList.add('page-exit');
                                                                                                                                                                                        
                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                      window.location.href = link.getAttribute('href');
                                                                                                                                                                                                            }, PAGE_TRANSITION_MS);
                                                                                                                                                                                                                });
                                                                                                                                                                                                                  });
                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                    // Reduced motion: strip the hidden initial state immediately so
                                                                                                                                                                                                                      // the page is just... there, with no animation and no delay.
                                                                                                                                                                                                                        document.body.classList.remove('page-enter');
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        /* ── Smooth anchor navigation ── */
                                                                                                                                                                                                                        document.querySelectorAll('a[href^="#"]').forEach((link) => {
                                                                                                                                                                                                                          link.addEventListener('click', (e) => {
                                                                                                                                                                                                                              const id = link.getAttribute('href');
                                                                                                                                                                                                                                  if (id.length < 2) return;
                                                                                                                                                                                                                                      const target = document.querySelector(id);
                                                                                                                                                                                                                                          if (!target) return;
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                              e.preventDefault();
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                  if (lenis) {
                                                                                                                                                                                                                                                        lenis.scrollTo(target, { offset: -84 });
                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                  target.scrollIntoView({
                                                                                                                                                                                                                                                                          behavior: prefersReducedMotion ? 'auto' : 'smooth',
                                                                                                                                                                                                                                                                                  block: 'start',
                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              /* ── Header shadow / mobile nav ── */
                                                                                                                                                                                                                                                                                              const header = document.getElementById('header');
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              window.addEventListener('scroll', () => {
                                                                                                                                                                                                                                                                                                header.classList.toggle('scrolled', window.scrollY > 8);
                                                                                                                                                                                                                                                                                                }, { passive: true });
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                const navToggle = document.getElementById('navToggle');
                                                                                                                                                                                                                                                                                                const nav       = document.getElementById('nav');
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                navToggle.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                  const opening = !nav.classList.contains('open');
                                                                                                                                                                                                                                                                                                    nav.classList.toggle('open', opening);
                                                                                                                                                                                                                                                                                                      navToggle.classList.toggle('open', opening);
                                                                                                                                                                                                                                                                                                        navToggle.setAttribute('aria-expanded', opening);
                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                        nav.querySelectorAll('.nav__link').forEach(link => {
                                                                                                                                                                                                                                                                                                          link.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                              nav.classList.remove('open');
                                                                                                                                                                                                                                                                                                                  navToggle.classList.remove('open');
                                                                                                                                                                                                                                                                                                                      navToggle.setAttribute('aria-expanded', 'false');
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                        document.addEventListener('click', (e) => {
                                                                                                                                                                                                                                                                                                                          if (nav.classList.contains('open') &&
                                                                                                                                                                                                                                                                                                                                !nav.contains(e.target) &&
                                                                                                                                                                                                                                                                                                                                      !navToggle.contains(e.target)) {
                                                                                                                                                                                                                                                                                                                                          nav.classList.remove('open');
                                                                                                                                                                                                                                                                                                                                              navToggle.classList.remove('open');
                                                                                                                                                                                                                                                                                                                                                  navToggle.setAttribute('aria-expanded', 'false');
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                    /* ── Active nav link — matches current page, not scroll position,
                                                                                                                                                                                                                                                                                                                                                       now that each nav item is its own HTML page ── */
                                                                                                                                                                                                                                                                                                                                                       const currentPage = location.pathname.split('/').pop() || 'index.html';
                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                       document.querySelectorAll('.nav__link').forEach(link => {
                                                                                                                                                                                                                                                                                                                                                         const linkPage = link.getAttribute('href').split('/').pop();
                                                                                                                                                                                                                                                                                                                                                           link.classList.toggle('active', linkPage === currentPage);
                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                           /* ── Contact form — placeholder handler (contact.html only) ──
                                                                                                                                                                                                                                                                                                                                                              Swap for a real handler (FormSubmit, EmailJS, or a custom API)
                                                                                                                                                                                                                                                                                                                                                                 when the business is ready to receive submissions. ── */
                                                                                                                                                                                                                                                                                                                                                                 const contactForm = document.getElementById('contactForm');
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                 if (contactForm) {
                                                                                                                                                                                                                                                                                                                                                                   contactForm.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                       e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                           const btn = contactForm.querySelector('button[type="submit"]');
                                                                                                                                                                                                                                                                                                                                                                               const originalText = btn.textContent;
                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                   btn.textContent = 'Message Sent';
                                                                                                                                                                                                                                                                                                                                                                                       btn.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                           contactForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                               setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                     btn.textContent = originalText;
                                                                                                                                                                                                                                                                                                                                                                                                           btn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                               }, 3000);
                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                 /* ── Hero entrance choreography + number count-up
                                                                                                                                                                                                                                                                                                                                                                                                                    (index.html only — guarded, no-op elsewhere) ── */
                                                                                                                                                                                                                                                                                                                                                                                                                    const heroSplit = document.querySelector('.hero');
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                    if (heroSplit) {
                                                                                                                                                                                                                                                                                                                                                                                                                      const runCountUp = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                          document.querySelectorAll('.js-count').forEach((el) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                const target = parseFloat(el.dataset.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                      const decimals = parseInt(el.dataset.decimals || '0', 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (Number.isNaN(target)) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (prefersReducedMotion) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          el.textContent = target.toFixed(decimals);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const duration = 1400;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const start = performance.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const tick = (now) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const p = Math.min(1, (now - start) / duration);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const eased = 1 - Math.pow(1 - p, 3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  el.textContent = (target * eased).toFixed(decimals);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (p < 1) requestAnimationFrame(tick);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      requestAnimationFrame(tick);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (prefersReducedMotion) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  heroSplit.classList.add('is-ready');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      runCountUp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            requestAnimationFrame(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  requestAnimationFrame(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    heroSplit.classList.add('is-ready');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(runCountUp, 850);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 80);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /* ── Scroll reveals ── */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const revealEls = document.querySelectorAll('.reveal');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (revealEls.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const revealObserver = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!entry.isIntersecting) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    entry.target.classList.add('visible');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          revealObserver.unobserve(entry.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, { threshold: 0.12 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  revealEls.forEach(el => revealObserver.observe(el));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
